-- OUTSINC Sample Data
-- Run this after database.sql to populate with sample data

-- Insert sample partner agencies
INSERT INTO agencies (name, description, phone, email, service_types, is_active) VALUES
('Four County Crisis', 'Mental health crisis support and intervention services', '1-866-995-9933', 'info@4countiescrisis.on.ca', ARRAY['crisis', 'mental_health'], true),
('Northumberland Community Legal Centre', 'Free legal services for low-income individuals', '905-372-0494', 'info@nclc.ca', ARRAY['legal', 'advocacy'], true),
('Hope Blooms Shelter', 'Emergency shelter and transitional housing', '905-555-0123', 'intake@hopeblooms.org', ARRAY['shelter', 'housing'], true),
('Community Health Centre', 'Primary healthcare and harm reduction services', '905-555-0456', 'info@chc.org', ARRAY['health', 'harm_reduction'], true);

-- Insert sample FAQs
INSERT INTO faq (question, answer, category, order_index, is_published) VALUES
('What is OUTSINC?', 'OUTSINC (Outreach Someone In Need of Change) is a lived-experience-led support and navigation service that helps people facing homelessness, substance use, mental health challenges, and other life crises connect with the right resources, at the right time, in a way that feels safe and human.', 'About OUTSINC', 1, true),
('Who can use OUTSINC services?', 'Anyone can use our services. You don''t need a diagnosis, referral, or "the right words" to ask for help. If something in your life isn''t working and you want support to change it - even a little - you''re welcome here.', 'Getting Started', 1, true),
('Is OUTSINC free?', 'Yes, all OUTSINC services are free. We believe that everyone deserves access to support regardless of income.', 'Getting Started', 2, true),
('How do I self-refer?', 'You can self-refer by clicking the "Self-Refer" button on our homepage and filling out a simple form. The process is private and respectful of your needs. You can skip any questions you''re not comfortable answering.', 'Getting Started', 3, true),
('What is harm reduction?', 'Harm reduction is an approach that meets people where they are. We support people who use substances in staying as safe as possible. We don''t require abstinence to offer help, and we don''t give up on people because of use.', 'Services', 1, true),
('Do I need to stop using substances to get help?', 'No. We practice harm reduction and believe you deserve support regardless of your substance use. We can help you stay safer, and if you want to reduce or stop using, we can explore options with you - but that''s your choice.', 'Services', 2, true),
('What happens to my information?', 'Your information is kept confidential and secure. You control who can access your information through our consent management system. We only share information with agencies you explicitly give permission to.', 'Privacy', 1, true),
('Can I change my consent preferences?', 'Yes! You can change your consent preferences at any time through your dashboard. You are always in control of who sees your information.', 'Privacy', 2, true),
('How do I report a concern?', 'Use the "Report" button on our homepage to submit reports about harm reduction litter, welfare checks, abandoned belongings, encampments, or safety concerns. All reports are handled with care for both safety and human dignity.', 'Community', 1, true),
('Can businesses partner with OUTSINC?', 'Yes! We offer consultation and training for businesses, schools, faith groups, and community organizations. Click "Partner With Us" to apply.', 'Community', 2, true);

-- Insert sample events
INSERT INTO events (title, description, event_type, location, start_datetime, end_datetime, capacity, is_public, registration_required) VALUES
('Community Lunch', 'Free lunch for everyone in the community. No registration needed, just show up!', 'community_lunch', 'Community Centre, 123 Main St', NOW() + INTERVAL '7 days', NOW() + INTERVAL '7 days' + INTERVAL '2 hours', NULL, true, false),
('Harm Reduction 101 Training', 'Learn the basics of harm reduction approaches and how to respond with compassion. This training is for volunteers, community members, and anyone interested in learning more.', 'training', 'OUTSINC Office, 456 Division St', NOW() + INTERVAL '14 days', NOW() + INTERVAL '14 days' + INTERVAL '3 hours', 20, true, true),
('Naloxone Training', 'Free training on how to recognize and respond to an opioid overdose using naloxone. Take-home kits provided.', 'harm_reduction', 'Community Health Centre', NOW() + INTERVAL '10 days', NOW() + INTERVAL '10 days' + INTERVAL '1 hour', 15, true, true),
('Business Response Workshop', 'A workshop for business owners on responding to visible homelessness and substance use with dignity and safety. Learn de-escalation techniques and compassionate policies.', 'workshop', 'Chamber of Commerce', NOW() + INTERVAL '21 days', NOW() + INTERVAL '21 days' + INTERVAL '2 hours', 30, true, true);

-- Insert sample blog posts
INSERT INTO posts (title, content, post_type, is_published, published_at) VALUES
('Welcome to OUTSINC', 'We are excited to launch OUTSINC, a new approach to supporting people in crisis. Our platform is built by people with lived experience, for people with lived experience. We believe that everyone deserves dignity, safety, and a place to belong - regardless of income, substance use, housing status, or what their life looks like right now. In the coming weeks, we will be rolling out new features and services. Stay tuned for updates!', 'news', true, NOW() - INTERVAL '7 days'),
('The Importance of Harm Reduction', 'Harm reduction is about meeting people where they are. It''s not about forcing anyone to change or stop using substances - it''s about keeping people as safe as possible while they navigate their own journey. This approach recognizes that substance use is complex and that abstinence isn''t realistic or desired for everyone. By providing safer use supplies, naloxone training, and non-judgmental support, we can save lives and build trust. Harm reduction is grounded in human rights and dignity, and it''s at the core of everything we do at OUTSINC.', 'blog', true, NOW() - INTERVAL '5 days'),
('January Impact Update', 'This month, we connected with 45 new clients, distributed 120 harm reduction kits, and responded to 23 community incident reports. Our outreach team logged over 200 hours on the streets, and we successfully housed 3 individuals. Thank you to our community partners and volunteers who make this work possible. Every connection matters, and together we are making a difference.', 'impact_update', true, NOW() - INTERVAL '2 days');

-- Insert sample courses
INSERT INTO courses (title, description, course_type, target_audience, content, duration_minutes, has_quiz, is_published) VALUES
('Understanding Homelessness', 'An introductory course on the causes and realities of homelessness in our community. Learn about systemic barriers, lived experience perspectives, and how you can help.', 'awareness', 'public', '<h3>What Causes Homelessness?</h3><p>Homelessness is not a choice - it''s the result of systemic failures. Key causes include:</p><ul><li>Lack of affordable housing</li><li>Low wages and inadequate social assistance</li><li>Mental health challenges</li><li>Substance use</li><li>Family breakdown</li><li>Leaving institutions (foster care, jail, hospitals) without support</li></ul><h3>Common Myths</h3><p><strong>Myth:</strong> People are homeless because they don''t want to work.<br><strong>Reality:</strong> Many people experiencing homelessness have jobs but can''t afford housing. Others face barriers to employment like lack of ID, mental health challenges, or criminal records.</p><p><strong>Myth:</strong> Just give them a house and the problem is solved.<br><strong>Reality:</strong> Housing is essential, but so is ongoing support. People need help navigating systems, accessing healthcare, and building stability.</p>', 30, true, true),
('Responding to an Overdose', 'Learn how to recognize the signs of an opioid overdose and how to respond using naloxone. This could save a life.', 'toolkit', 'volunteer', '<h3>Signs of an Opioid Overdose</h3><ul><li>Unconsciousness or inability to wake up</li><li>Slow or no breathing</li><li>Blue or purple lips/fingernails</li><li>Choking or gurgling sounds</li><li>Very small (pinpoint) pupils</li></ul><h3>How to Respond</h3><ol><li><strong>Call 911</strong> - Do this first!</li><li><strong>Give naloxone</strong> if available (nasal spray or injection)</li><li><strong>Do rescue breathing</strong> if trained</li><li><strong>Stay with them</strong> until help arrives</li></ol><h3>Good Samaritan Law</h3><p>In Ontario, the Good Samaritan Drug Overdose Act provides legal protection for anyone who calls 911 during an overdose. You cannot be charged for simple drug possession if you are seeking emergency help.</p>', 15, false, true),
('Trauma-Informed Practice Basics', 'An introduction to trauma-informed approaches for frontline workers, volunteers, and community members. Learn how to create safer, more supportive interactions.', 'course', 'volunteer', '<h3>What is Trauma?</h3><p>Trauma is a response to deeply distressing or disturbing events that overwhelm a person''s ability to cope. It can be a single event or repeated experiences. Common sources of trauma include violence, abuse, loss, poverty, discrimination, and systemic oppression.</p><h3>Core Principles of Trauma-Informed Care</h3><ul><li><strong>Safety:</strong> Physical and emotional safety</li><li><strong>Trustworthiness:</strong> Clear, consistent boundaries</li><li><strong>Choice:</strong> Support autonomy and self-determination</li><li><strong>Collaboration:</strong> Share power and decision-making</li><li><strong>Empowerment:</strong> Focus on strengths, not deficits</li></ul><h3>Practical Tips</h3><ul><li>Explain what you''re doing and why</li><li>Ask before touching</li><li>Offer choices whenever possible</li><li>Be patient with repetition</li><li>Don''t take behavior personally</li><li>Believe people''s experiences</li></ul>', 45, true, true),
('How to Apply for ODSP', 'Step-by-step guide to applying for Ontario Disability Support Program benefits.', 'howto', 'public', '<h3>What is ODSP?</h3><p>The Ontario Disability Support Program provides financial and employment assistance to people with disabilities. Benefits include monthly income support and health benefits.</p><h3>Eligibility</h3><p>You must:</p><ul><li>Be 18 years or older</li><li>Live in Ontario</li><li>Be a Canadian citizen or have legal status</li><li>Have a disability that is continuous or recurring, expected to last a year or more, and substantially limits your ability to work or care for yourself</li></ul><h3>Application Process</h3><ol><li>Complete the application package</li><li>Get the Disability Determination Package completed by a medical professional</li><li>Submit all forms to your local ODSP office</li><li>Attend an interview if requested</li><li>Wait for a decision (can take 3-6 months)</li></ol><p><em>Need help? OUTSINC workers can assist with filling out forms and gathering documentation.</em></p>', 20, false, true);
